/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performance;

import performance.*;
import java.awt.Color;

/**
 *
 * @author Jose Felipe
 */
public class UpdatePerformanceEmployee extends javax.swing.JFrame {

    private ViewPerformance performance; 
    
    public UpdatePerformanceEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameEmploye = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boxObjetives = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        boxQuality = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        boxResults = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        boxComunications = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boxGrowth = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        boxSkills = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        boxKnowing = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        boxRelatioships = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fieldIndex = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 65, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar desempeño");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 610, -1));

        nameEmploye.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameEmploye.setForeground(new java.awt.Color(51, 51, 51));
        nameEmploye.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameEmploye.setText("Empleado");
        jPanel1.add(nameEmploye, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 610, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Capacidad de comunicacion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 190, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 10));

        fieldDate.setBackground(new java.awt.Color(220, 220, 220));
        fieldDate.setBorder(null);
        jPanel1.add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 32));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese la fecha actual (DD/MM/AA):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        boxObjetives.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Si", "No" }));
        jPanel1.add(boxObjetives, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 32));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Cumplio los objetivos asignados:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        boxQuality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Excelente", "Bueno", "Malo" }));
        jPanel1.add(boxQuality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, 32));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Resultado de los objetivos asignados:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        boxResults.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Excelentes", "Buenos", "Normales", "Malos" }));
        jPanel1.add(boxResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, 32));

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Calida del trabajo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        boxComunications.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Excelente", "Alta", "Normal", "Baja" }));
        jPanel1.add(boxComunications, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 110, 32));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Potencial de crecimiento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        boxGrowth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alto", "Medio", "Bajo" }));
        jPanel1.add(boxGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, 32));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Habiliades tecnicas:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 120, -1));

        boxSkills.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Excelentes", "Buenas", "Normales", "Malas" }));
        jPanel1.add(boxSkills, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 110, 32));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Conocimiento del puesto:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 150, -1));

        boxKnowing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alto", "Medio", "Bajo" }));
        jPanel1.add(boxKnowing, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 110, 32));

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Realacion con sus compañeros:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 190, -1));

        boxRelatioships.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Excelente", "Alta", "Normal", "Baja" }));
        jPanel1.add(boxRelatioships, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 110, 32));

        btnUpdate.setBackground(new java.awt.Color(255, 65, 65));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Actualizar");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, 34));

        btnBack.setBackground(new java.awt.Color(255, 65, 65));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Regresar");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, -1));

        fieldIndex.setBackground(new java.awt.Color(220, 220, 220));
        fieldIndex.setBorder(null);
        jPanel1.add(fieldIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 120, 32));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Id evaluacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        this.btnBack.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        this.btnBack.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        this.btnUpdate.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
       this.btnUpdate.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.performance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        String fullfilled = this.boxObjetives.getSelectedItem().toString();
        String result = this.boxResults.getSelectedItem().toString();
        String quality  = this.boxResults.getSelectedItem().toString();
        String growth = this.boxGrowth.getSelectedItem().toString();
        String skills = this.boxSkills.getSelectedItem().toString();
        String knoPosition = this.boxKnowing.getSelectedItem().toString();
        String relatioships = this.boxRelatioships.getSelectedItem().toString();
        String comunication = this.boxComunications.getSelectedItem().toString();
        String date = this.fieldDate.getText();
        String index = this.fieldIndex.getText();
        
        if(index.trim().isEmpty()){
            showMessage("Error debe ingresar el ID de la evaluacion que quiere actualizar.");
        }else{
           this.performance.updatePerformanceEmployee(Integer.parseInt(index),fullfilled, result, quality, growth, skills, knoPosition, relatioships, comunication, date); 
        }
        
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePerformanceEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePerformanceEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePerformanceEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePerformanceEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePerformanceEmployee().setVisible(true);
            }
        });
    }
    public void resetData(){
        this.boxObjetives.setSelectedIndex(0);
        this.boxResults.setSelectedIndex(0);
        this.boxResults.setSelectedIndex(0);
        this.boxGrowth.setSelectedIndex(0);
        this.boxSkills.setSelectedIndex(0);
        this.boxKnowing.setSelectedIndex(0);
        this.boxRelatioships.setSelectedIndex(0);
        this.boxComunications.setSelectedIndex(0);
        this.fieldDate.setText("");
        this.fieldIndex.setText("");
    }
    
    public void setNameEmployee(String name){
        this.nameEmploye.setText(name);
    }
    
    public void setPerformance(ViewPerformance per){
        this.performance = per;
    }
    
    public void showMessage(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxComunications;
    private javax.swing.JComboBox<String> boxGrowth;
    private javax.swing.JComboBox<String> boxKnowing;
    private javax.swing.JComboBox<String> boxObjetives;
    private javax.swing.JComboBox<String> boxQuality;
    private javax.swing.JComboBox<String> boxRelatioships;
    private javax.swing.JComboBox<String> boxResults;
    private javax.swing.JComboBox<String> boxSkills;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldIndex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameEmploye;
    // End of variables declaration//GEN-END:variables
}
