/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package performance;
import employees.Employee;
import employees.Employees;
import java.awt.Color;
import java.util.ArrayList;
import manager.Manager;

/**
 *
 * @author Jose Felipe
 */
public class ViewPerformance extends javax.swing.JFrame {

    private ArrayList<Employee> employees;
    private Manager manager;
    private ModelPerformance model;
    private ControllerPerformance controller;
    private AddPerformanceEmployee addEmployee;
    private ReadPerformanceEmployee readEmployee;
    private DeletePerformanceEmployee deletEmployee;
    private UpdatePerformanceEmployee updatePerformance;
    
    public ViewPerformance() {
        initComponents();
        this.setLocationRelativeTo(null);  
    }
    
    public void setEmployees(Employees emp){
        //this.employees = emp.getEmployees();
        
        this.model = new ModelPerformance(emp);
        this.addEmployee = new AddPerformanceEmployee();
        this.readEmployee = new ReadPerformanceEmployee();
        this.deletEmployee = new DeletePerformanceEmployee();
        this.updatePerformance = new UpdatePerformanceEmployee();
        this.controller = new ControllerPerformance(this,model,addEmployee,deletEmployee, updatePerformance);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSearchEmployee = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchDepartament = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fieldDocument = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cardSalaryEmp = new javax.swing.JLabel();
        cardDocumentEmp = new javax.swing.JLabel();
        cardTemporaryEmp = new javax.swing.JLabel();
        cardPostEmp = new javax.swing.JLabel();
        cardTelEmp = new javax.swing.JLabel();
        cardDateEmp = new javax.swing.JLabel();
        cardNameEmp = new javax.swing.JLabel();
        cardLastNameEmp = new javax.swing.JLabel();
        btnAddEmp = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSearchEmp = new javax.swing.JPanel();
        txtSearchEmp = new javax.swing.JLabel();
        btnUpdateEmp = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnDeletEmployee = new javax.swing.JPanel();
        txtDeletEmployee = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUsers.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Panel de gestion de desempeño");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Bienvenid@");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 70));

        btnBack.setBackground(new java.awt.Color(255, 65, 65));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Regresar");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBackLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 130, 34));

        btnSearchEmployee.setBackground(new java.awt.Color(255, 65, 65));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchEmployeeLayout = new javax.swing.GroupLayout(btnSearchEmployee);
        btnSearchEmployee.setLayout(btnSearchEmployeeLayout);
        btnSearchEmployeeLayout.setHorizontalGroup(
            btnSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchEmployeeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSearchEmployeeLayout.setVerticalGroup(
            btnSearchEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchEmployeeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSearchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 120, 34));

        btnSearchDepartament.setBackground(new java.awt.Color(255, 65, 65));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consultar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchDepartamentLayout = new javax.swing.GroupLayout(btnSearchDepartament);
        btnSearchDepartament.setLayout(btnSearchDepartamentLayout);
        btnSearchDepartamentLayout.setHorizontalGroup(
            btnSearchDepartamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchDepartamentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSearchDepartamentLayout.setVerticalGroup(
            btnSearchDepartamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchDepartamentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSearchDepartament, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 120, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N

        fieldDocument.setBackground(new java.awt.Color(255, 255, 255));
        fieldDocument.setForeground(new java.awt.Color(102, 102, 102));
        fieldDocument.setText("Buscar empleado por cedula..");
        fieldDocument.setBorder(null);
        fieldDocument.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldDocumentMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(fieldDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 34));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setText("Buscar departamento por Id..");
        jTextField1.setBorder(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 220, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 65, 65));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 220));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardUser1.png"))); // NOI18N
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        cardSalaryEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardSalaryEmp.setText("Salario");
        jPanel9.add(cardSalaryEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        cardDocumentEmp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cardDocumentEmp.setForeground(new java.awt.Color(255, 65, 65));
        cardDocumentEmp.setText("Documento");
        jPanel9.add(cardDocumentEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        cardTemporaryEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardTemporaryEmp.setText("Temporal");
        jPanel9.add(cardTemporaryEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        cardPostEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardPostEmp.setText("Cargo");
        jPanel9.add(cardPostEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        cardTelEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardTelEmp.setText("Telefono");
        jPanel9.add(cardTelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        cardDateEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardDateEmp.setText("Fecha ingreso");
        jPanel9.add(cardDateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        cardNameEmp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cardNameEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardNameEmp.setText("Empleado");
        jPanel9.add(cardNameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        cardLastNameEmp.setForeground(new java.awt.Color(51, 51, 51));
        cardLastNameEmp.setText("Apellido");
        jPanel9.add(cardLastNameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnAddEmp.setBackground(new java.awt.Color(255, 65, 65));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Agregar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddEmpLayout = new javax.swing.GroupLayout(btnAddEmp);
        btnAddEmp.setLayout(btnAddEmpLayout);
        btnAddEmpLayout.setHorizontalGroup(
            btnAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnAddEmpLayout.setVerticalGroup(
            btnAddEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel9.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 32));

        btnSearchEmp.setBackground(new java.awt.Color(255, 65, 65));

        txtSearchEmp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSearchEmp.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSearchEmp.setText("Consultar");
        txtSearchEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSearchEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchEmpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchEmpLayout = new javax.swing.GroupLayout(btnSearchEmp);
        btnSearchEmp.setLayout(btnSearchEmpLayout);
        btnSearchEmpLayout.setHorizontalGroup(
            btnSearchEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearchEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnSearchEmpLayout.setVerticalGroup(
            btnSearchEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearchEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel9.add(btnSearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btnUpdateEmp.setBackground(new java.awt.Color(255, 65, 65));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Actualizar");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUpdateEmpLayout = new javax.swing.GroupLayout(btnUpdateEmp);
        btnUpdateEmp.setLayout(btnUpdateEmpLayout);
        btnUpdateEmpLayout.setHorizontalGroup(
            btnUpdateEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnUpdateEmpLayout.setVerticalGroup(
            btnUpdateEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel9.add(btnUpdateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnDeletEmployee.setBackground(new java.awt.Color(255, 65, 65));

        txtDeletEmployee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtDeletEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txtDeletEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDeletEmployee.setText("Eliminar");
        txtDeletEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDeletEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDeletEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDeletEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDeletEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDeletEmployeeLayout = new javax.swing.GroupLayout(btnDeletEmployee);
        btnDeletEmployee.setLayout(btnDeletEmployeeLayout);
        btnDeletEmployeeLayout.setHorizontalGroup(
            btnDeletEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDeletEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnDeletEmployeeLayout.setVerticalGroup(
            btnDeletEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDeletEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel9.add(btnDeletEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 360, 220));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 65, 65));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 220));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 360, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        this.btnBack.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        this.btnBack.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        this.btnSearchDepartament.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        this.btnSearchDepartament.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        this.btnSearchEmployee.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        this.btnSearchEmployee.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel6MouseExited

    private void txtSearchEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchEmpMouseEntered
       this.btnSearchEmp.setBackground(new Color(200,50,50)); 
    }//GEN-LAST:event_txtSearchEmpMouseEntered

    private void txtSearchEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchEmpMouseExited
        this.btnSearchEmp.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtSearchEmpMouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
         this.btnUpdateEmp.setBackground(new Color(200,50,50)); 
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        this.btnUpdateEmp.setBackground(new Color(255,65,65)); 
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        this.btnAddEmp.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        this.btnAddEmp.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_jLabel10MouseExited

    private void txtSearchEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchEmpMouseClicked
        String document = this.controller.getDocument();
        Employee emp = this.controller.viewPerformance();
        
        if(document != ""){
            this.readEmployee.setVPerformance(this);
            this.readEmployee.setNameEmployee(emp.getName()+" "+emp.getLastName());
            this.readEmployee.setPerformance(emp.getPerformance());
            this.readEmployee.setVisible(true);
            this.setVisible(false);
            
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }
    }//GEN-LAST:event_txtSearchEmpMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.controller.searchEmployee();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void fieldDocumentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldDocumentMousePressed
        this.fieldDocument.setText("");
        this.fieldDocument.setForeground(Color.black);
    }//GEN-LAST:event_fieldDocumentMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.manager.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String document = this.controller.getDocument();
        
        if(document != ""){
            this.addEmployee.setPerformance(this);
            this.addEmployee.setVisible(true);
            this.setVisible(false); 
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }

    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtDeletEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeletEmployeeMouseClicked
        String document = this.controller.getDocument();
        Employee emp = this.controller.viewPerformance();
        
        if(document != ""){
            this.deletEmployee.setPerformance(this);
            this.deletEmployee.setNameEmployee(emp.getName()+" "+emp.getLastName());
            this.deletEmployee.setVisible(true);
            this.setVisible(false);
            
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }
    }//GEN-LAST:event_txtDeletEmployeeMouseClicked

    private void txtDeletEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeletEmployeeMouseEntered
        this.txtDeletEmployee.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtDeletEmployeeMouseEntered

    private void txtDeletEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeletEmployeeMouseExited
        this.txtDeletEmployee.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtDeletEmployeeMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        String document = this.controller.getDocument();
        Employee emp = this.controller.viewPerformance();
        
        if(document != ""){
            this.updatePerformance.setPerformance(this);
            this.updatePerformance.setNameEmployee(emp.getName()+" "+emp.getLastName());
            this.updatePerformance.setVisible(true);
            this.setVisible(false);
            
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPerformance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPerformance().setVisible(true);
            }
        });
    }
    public void deletePerformanceEmploye(int index){
        this.controller.deletePerformanceEmployee(index);
    }
    
    public void updatePerformanceEmployee(int index,String fullfilled, String result, String quality, String growth,
                       String skills, String knoPosition,String relatioships, String comunication,String date){
        this.controller.updatePerformanceEmployee(index,fullfilled, result, quality, growth, skills, knoPosition, relatioships, comunication, date);
    }
    
    public void addPerfEmployee(String fullfilled, String result, String quality, String growth,
                       String skills, String knoPosition,String relatioships, String comunication,String date){
        this.controller.addPerformanceEmployee(fullfilled, result, quality, growth, skills, knoPosition, relatioships, comunication, date);
    }
    
    public void setManager(Manager manager){
        this.manager = manager;
    }
    
    public void setFieldDocument(){
        this.fieldDocument.setText("Buscar empleado por cedula..");
        this.fieldDocument.setForeground(Color.gray);
    }
    
    public void setEmployeeToCard(Employee emp){
        this.cardNameEmp.setText(emp.getName());
        this.cardLastNameEmp.setText(emp.getLastName());
        this.cardPostEmp.setText("Cargo: "+emp.getPost());
        this.cardDocumentEmp.setText("C.C: "+emp.getDocument());
        this.cardTelEmp.setText("Cel: "+emp.getPhone());
        this.cardSalaryEmp.setText("Salario: "+emp.getSalary());
        this.cardDateEmp.setText("Ingreso: "+emp.getEntryDate());
        this.cardTemporaryEmp.setText("Temporal: "+emp.getTemporary());
        
    }
    
    public String getDocument(){
       return this.fieldDocument.getText();
    }
    
    public void showMessage(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddEmp;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnDeletEmployee;
    private javax.swing.JPanel btnSearchDepartament;
    private javax.swing.JPanel btnSearchEmp;
    private javax.swing.JPanel btnSearchEmployee;
    private javax.swing.JPanel btnUpdateEmp;
    private javax.swing.JLabel cardDateEmp;
    private javax.swing.JLabel cardDocumentEmp;
    private javax.swing.JLabel cardLastNameEmp;
    private javax.swing.JLabel cardNameEmp;
    private javax.swing.JLabel cardPostEmp;
    private javax.swing.JLabel cardSalaryEmp;
    private javax.swing.JLabel cardTelEmp;
    private javax.swing.JLabel cardTemporaryEmp;
    private javax.swing.JTextField fieldDocument;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txtDeletEmployee;
    private javax.swing.JLabel txtSearchEmp;
    // End of variables declaration//GEN-END:variables
}
