/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employees;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import manager.Manager;
/**
 *
 * @author Jose Felipe
 */
public class Employees extends javax.swing.JFrame {

    private ArrayList<Employee> employees;
    private ViewAddEmployee addEmp;
    private ViewUpdateEmployee updateEmp;
    private ControllerEmployees controller;
    private ViewPerformance performance;
    private Manager manager;
    
    public Employees() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.employees = new ArrayList<>();
        
        ModelEmployees model = new ModelEmployees(this);
        this.addEmp = new ViewAddEmployee();
        this.updateEmp = new ViewUpdateEmployee();
        this.performance = new ViewPerformance();
        this.controller = new ControllerEmployees(this,model,addEmp,updateEmp);
        
        showEmployeesToTable();
    }
    
    
    public void showEmployeesToTable(){
        String[] colums = {"Nombre", "Apellido", "Documento","Cargo","Telefono", "Salario","Fecha ingreso","Temporal"};
        // Crear modelo vacío con columnas
        DefaultTableModel model = new DefaultTableModel(null, colums);
        
        // Recorrer arrayList y agregar filas
        for (Employee u : employees) {
        Object[] row = {u.getName(), u.getLastName(), u.getDocument(),u.getPost(),u.getPhone(),u.getSalary(),u.getEntryDate(),u.getTemporary()};
        model.addRow(row);
        }
        // Asignar modelo a la JTable
        this.tblEmployees.setModel(model);
    }
    
    public ArrayList<Employee> getEmployees(){
        return this.employees;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCloseSesion = new javax.swing.JPanel();
        txtCloseSesion = new javax.swing.JLabel();
        btnAdd = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JLabel();
        btnSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CardName = new javax.swing.JLabel();
        cardLastName = new javax.swing.JLabel();
        cardDocument = new javax.swing.JLabel();
        cardPost = new javax.swing.JLabel();
        cardPhone = new javax.swing.JLabel();
        cardEntryDate = new javax.swing.JLabel();
        cardSalary = new javax.swing.JLabel();
        cardTemporary = new javax.swing.JLabel();
        cardBtnUpdate = new javax.swing.JPanel();
        cardTxtUpdate = new javax.swing.JLabel();
        cardBtnDelet = new javax.swing.JPanel();
        cardTxtDelet = new javax.swing.JLabel();
        cardBtnPerformance = new javax.swing.JPanel();
        cardTxtPerformance = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUsers.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Panel de gestion de empleados CompuWork");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Bienvenid@");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 65, 65));
        jSeparator1.setForeground(new java.awt.Color(255, 65, 65));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 10));

        btnCloseSesion.setBackground(new java.awt.Color(255, 65, 65));

        txtCloseSesion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        txtCloseSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCloseSesion.setText("Regresar");
        txtCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseSesionLayout = new javax.swing.GroupLayout(btnCloseSesion);
        btnCloseSesion.setLayout(btnCloseSesionLayout);
        btnCloseSesionLayout.setHorizontalGroup(
            btnCloseSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCloseSesionLayout.setVerticalGroup(
            btnCloseSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseSesionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCloseSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnCloseSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 110, 35));

        btnAdd.setBackground(new java.awt.Color(255, 65, 65));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_add.png"))); // NOI18N

        txtAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAdd.setText("Agregar Empleado");
        txtAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAddMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddLayout = new javax.swing.GroupLayout(btnAdd);
        btnAdd.setLayout(btnAddLayout);
        btnAddLayout.setHorizontalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );
        btnAddLayout.setVerticalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnAddLayout.createSequentialGroup()
                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 35));

        btnSearch.setBackground(new java.awt.Color(255, 65, 65));

        txtSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSearch.setText("Consultar");
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 34));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 65, 65));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 210));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardUser1.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 50));

        CardName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CardName.setForeground(new java.awt.Color(51, 51, 51));
        CardName.setText("Empleado");
        jPanel7.add(CardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        cardLastName.setForeground(new java.awt.Color(51, 51, 51));
        cardLastName.setText("Apellido");
        jPanel7.add(cardLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        cardDocument.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cardDocument.setForeground(new java.awt.Color(255, 65, 65));
        cardDocument.setText("Documento");
        jPanel7.add(cardDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, -1));

        cardPost.setForeground(new java.awt.Color(51, 51, 51));
        cardPost.setText("Cargo");
        jPanel7.add(cardPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        cardPhone.setForeground(new java.awt.Color(51, 51, 51));
        cardPhone.setText("Telefono");
        jPanel7.add(cardPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        cardEntryDate.setForeground(new java.awt.Color(51, 51, 51));
        cardEntryDate.setText("Fecha Ingreso");
        jPanel7.add(cardEntryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        cardSalary.setForeground(new java.awt.Color(51, 51, 51));
        cardSalary.setText("Salario");
        jPanel7.add(cardSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        cardTemporary.setForeground(new java.awt.Color(51, 51, 51));
        cardTemporary.setText("Temporal");
        jPanel7.add(cardTemporary, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        cardBtnUpdate.setBackground(new java.awt.Color(255, 65, 65));

        cardTxtUpdate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cardTxtUpdate.setForeground(new java.awt.Color(255, 255, 255));
        cardTxtUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTxtUpdate.setText("Actualizar");
        cardTxtUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardTxtUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardTxtUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardTxtUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardTxtUpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cardBtnUpdateLayout = new javax.swing.GroupLayout(cardBtnUpdate);
        cardBtnUpdate.setLayout(cardBtnUpdateLayout);
        cardBtnUpdateLayout.setHorizontalGroup(
            cardBtnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        cardBtnUpdateLayout.setVerticalGroup(
            cardBtnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel7.add(cardBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 33));

        cardBtnDelet.setBackground(new java.awt.Color(255, 65, 65));

        cardTxtDelet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cardTxtDelet.setForeground(new java.awt.Color(255, 255, 255));
        cardTxtDelet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTxtDelet.setText("Eliminar");
        cardTxtDelet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardTxtDelet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardTxtDeletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardTxtDeletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardTxtDeletMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cardBtnDeletLayout = new javax.swing.GroupLayout(cardBtnDelet);
        cardBtnDelet.setLayout(cardBtnDeletLayout);
        cardBtnDeletLayout.setHorizontalGroup(
            cardBtnDeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtDelet, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        cardBtnDeletLayout.setVerticalGroup(
            cardBtnDeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtDelet, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel7.add(cardBtnDelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        cardBtnPerformance.setBackground(new java.awt.Color(255, 65, 65));

        cardTxtPerformance.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cardTxtPerformance.setForeground(new java.awt.Color(255, 255, 255));
        cardTxtPerformance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTxtPerformance.setText("Desempeño");
        cardTxtPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardTxtPerformance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardTxtPerformanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardTxtPerformanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardTxtPerformanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cardBtnPerformanceLayout = new javax.swing.GroupLayout(cardBtnPerformance);
        cardBtnPerformance.setLayout(cardBtnPerformanceLayout);
        cardBtnPerformanceLayout.setHorizontalGroup(
            cardBtnPerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtPerformance, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        cardBtnPerformanceLayout.setVerticalGroup(
            cardBtnPerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardTxtPerformance, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel7.add(cardBtnPerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 360, 210));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N

        fieldSearch.setBackground(new java.awt.Color(255, 255, 255));
        fieldSearch.setForeground(new java.awt.Color(153, 153, 153));
        fieldSearch.setText("Buscar empleado por cedula...");
        fieldSearch.setBorder(null);
        fieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldSearchMousePressed(evt);
            }
        });
        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 230, 32));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_small.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 180, 180));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmployees);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 570, 210));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Lista de empleados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void txtCloseSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseEntered
        this.btnCloseSesion.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtCloseSesionMouseEntered

    private void txtCloseSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseExited
        this.btnCloseSesion.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtCloseSesionMouseExited

    private void txtAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddMouseEntered
        this.btnAdd.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtAddMouseEntered

    private void txtAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddMouseExited
        this.btnAdd.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtAddMouseExited

    private void txtSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseEntered
         this.btnSearch.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtSearchMouseEntered

    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited
        this.btnSearch.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtSearchMouseExited

    private void cardTxtUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtUpdateMouseEntered
        this.cardBtnUpdate.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_cardTxtUpdateMouseEntered

    private void cardTxtUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtUpdateMouseExited
        this.cardBtnUpdate.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_cardTxtUpdateMouseExited

    private void cardTxtDeletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtDeletMouseEntered
        this.cardBtnDelet.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_cardTxtDeletMouseEntered

    private void cardTxtDeletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtDeletMouseExited
        this.cardBtnDelet.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_cardTxtDeletMouseExited

    private void cardTxtPerformanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtPerformanceMouseEntered
        this.cardBtnPerformance.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_cardTxtPerformanceMouseEntered

    private void cardTxtPerformanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtPerformanceMouseExited
        this.cardBtnPerformance.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_cardTxtPerformanceMouseExited

    private void fieldSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldSearchMousePressed
        this.fieldSearch.setText("");
        this.fieldSearch.setForeground(Color.black);
    }//GEN-LAST:event_fieldSearchMousePressed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
       this.controller.searchEmployee();
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddMouseClicked
        this.addEmp.setEmployees(this);
        this.addEmp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtAddMouseClicked

    private void cardTxtUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtUpdateMouseClicked
        String document = this.controller.getDocument();
        
        if(document != ""){
            this.updateEmp.setEmployee(this);
            this.updateEmp.setName(this.CardName.getText());
            this.updateEmp.setVisible(true);
            this.setVisible(false);
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }
        
    }//GEN-LAST:event_cardTxtUpdateMouseClicked

    private void cardTxtDeletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtDeletMouseClicked
       
        this.controller.removeEmployee();  
    }//GEN-LAST:event_cardTxtDeletMouseClicked

    private void cardTxtPerformanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardTxtPerformanceMouseClicked
        String document = this.controller.getDocument();
        Employee emp = this.controller.viewPerformance();
        
        if(document != ""){
            this.performance.setEmployee(this);
            this.performance.setNameEmployee(emp.getName()+" "+emp.getLastName());
            this.performance.setPerformance(emp.getPerformance());
            this.performance.setVisible(true);
            this.setVisible(false);
            
        }else {
            this.showMessage("¡Error no se ha realizado ninguna busqueda!");
        }
    }//GEN-LAST:event_cardTxtPerformanceMouseClicked

    private void txtCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseClicked
        this.manager.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtCloseSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }
    
    public void setManager(Manager manager){
        this.manager = manager;
    }
    
    public void createEmployee(String document,String name,String lastName, 
            String post,String phone,String date,String salary,String temporary){
        
        this.controller.createEmployee(document, name, lastName, post, phone, date, salary, temporary);
    }
    
    public void updateEmployee(String document,String name,String lastName, 
            String post,String phone,String date,String salary,String temporary){
        
        this.controller.updateEmployee(document, name, lastName, post, phone, date, salary, temporary);
    }
    
    public void resetFieldSearch(){
        this.fieldSearch.setText("Buscar empleado por cedula...");
        this.fieldSearch.setForeground(Color.gray);
    }
    
    public String getDocument(){
        return this.fieldSearch.getText();
    }
    
    public void resetToCard(){
        this.CardName.setText("Empleado");
        this.cardLastName.setText("Apellido");
        this.cardPost.setText("Cargo");
        this.cardDocument.setText("Documento");
        this.cardPhone.setText("Telefono");
        this.cardSalary.setText("Salario");
        this.cardEntryDate.setText("Fecha ingreso");
        this.cardTemporary.setText("Temporal");   
    }
    
    public void setEmployeeToCard(Employee emp){
        this.CardName.setText(emp.getName());
        this.cardLastName.setText(emp.getLastName());
        this.cardPost.setText("Cargo: "+emp.getPost());
        this.cardDocument.setText("C.C: "+emp.getDocument());
        this.cardPhone.setText("Cel: "+emp.getPhone());
        this.cardSalary.setText("Salario: "+emp.getSalary());
        this.cardEntryDate.setText("Ingreso: "+emp.getEntryDate());
        this.cardTemporary.setText("Temporal: "+emp.getTemporary());
        
    }
    
    public String confirmRemove(String name){
        String [] buttons = {"Si","No"};
        String error = "Seguro que desea eliminar al empleado "+name;
        
       int option = javax.swing.JOptionPane.showOptionDialog(null,error,"Eliminar empleado",0,JOptionPane.QUESTION_MESSAGE,null,buttons,"No");
        
        return buttons[option];
    }
    
    
    public void showMessage(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardName;
    private javax.swing.JPanel btnAdd;
    private javax.swing.JPanel btnCloseSesion;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JPanel cardBtnDelet;
    private javax.swing.JPanel cardBtnPerformance;
    private javax.swing.JPanel cardBtnUpdate;
    private javax.swing.JLabel cardDocument;
    private javax.swing.JLabel cardEntryDate;
    private javax.swing.JLabel cardLastName;
    private javax.swing.JLabel cardPhone;
    private javax.swing.JLabel cardPost;
    private javax.swing.JLabel cardSalary;
    private javax.swing.JLabel cardTemporary;
    private javax.swing.JLabel cardTxtDelet;
    private javax.swing.JLabel cardTxtPerformance;
    private javax.swing.JLabel cardTxtUpdate;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JLabel txtAdd;
    private javax.swing.JLabel txtCloseSesion;
    private javax.swing.JLabel txtSearch;
    // End of variables declaration//GEN-END:variables
}
