/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employees;

import java.awt.Color;

/**
 *
 * @author Jose Felipe
 */
public class ViewAddEmployee extends javax.swing.JFrame {

    private Employees employee;
    
    public ViewAddEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        fieldPhone = new javax.swing.JTextField();
        fieldSalary = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldDocument = new javax.swing.JTextField();
        fieldPost = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldEntryDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxTermporary = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnAddEmployee = new javax.swing.JPanel();
        txtAddEmployee = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        txtBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setForeground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 65, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar empleados CompuWork");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 40));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 10));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 10));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 10));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 10));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 180, 10));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 180, -1));

        fieldPhone.setBackground(new java.awt.Color(220, 220, 220));
        fieldPhone.setBorder(null);
        jPanel1.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, 32));

        fieldSalary.setBackground(new java.awt.Color(220, 220, 220));
        fieldSalary.setBorder(null);
        jPanel1.add(fieldSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 180, 32));

        fieldLastName.setBackground(new java.awt.Color(220, 220, 220));
        fieldLastName.setBorder(null);
        jPanel1.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 32));

        fieldDocument.setBackground(new java.awt.Color(220, 220, 220));
        fieldDocument.setBorder(null);
        jPanel1.add(fieldDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 32));

        fieldPost.setBackground(new java.awt.Color(220, 220, 220));
        fieldPost.setBorder(null);
        jPanel1.add(fieldPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 32));

        fieldName.setBackground(new java.awt.Color(220, 220, 220));
        fieldName.setBorder(null);
        jPanel1.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 32));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Ingresa el numero de telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ingresa el nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Ingresa el apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("¿Es temporal?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Ingresa el cargo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Ingresa el numero de documento:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_small.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 210, 170));

        fieldEntryDate.setBackground(new java.awt.Color(220, 220, 220));
        fieldEntryDate.setBorder(null);
        jPanel1.add(fieldEntryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 180, 32));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ingresa la fecha de ingreso (DD/MM/AA):");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        boxTermporary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir opcion", "Si", "No" }));
        jPanel1.add(boxTermporary, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 32));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Ingresa el salario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        btnAddEmployee.setBackground(new java.awt.Color(255, 65, 65));

        txtAddEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        txtAddEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAddEmployee.setText("Agregar");
        txtAddEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAddEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAddEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAddEmployeeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAddEmployeeLayout = new javax.swing.GroupLayout(btnAddEmployee);
        btnAddEmployee.setLayout(btnAddEmployeeLayout);
        btnAddEmployeeLayout.setHorizontalGroup(
            btnAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAddEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnAddEmployeeLayout.setVerticalGroup(
            btnAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, 35));

        btnBack.setBackground(new java.awt.Color(255, 65, 65));

        txtBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBack.setForeground(new java.awt.Color(255, 255, 255));
        txtBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBack.setText("Regresar");
        txtBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseEntered
        this.btnBack.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtBackMouseEntered

    private void txtBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseExited
        this.btnBack.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtBackMouseExited

    private void txtAddEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEmployeeMouseEntered
       this.btnAddEmployee.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtAddEmployeeMouseEntered

    private void txtAddEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEmployeeMouseExited
         this.btnAddEmployee.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtAddEmployeeMouseExited

    private void txtBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseClicked
        this.employee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtBackMouseClicked

    private void txtAddEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddEmployeeMouseClicked
        String name = this.fieldName.getText();
        String lastName = this.fieldLastName.getText();
        String document = this.fieldDocument.getText();
        String post = this.fieldPost.getText();
        String phone = this.fieldPhone.getText();
        String date = this.fieldEntryDate.getText();
        String salary = this.fieldSalary.getText();
        String temporary = this.boxTermporary.getSelectedItem().toString();
        
        this.employee.createEmployee(document, name, lastName, post, phone, date, salary, temporary);
    }//GEN-LAST:event_txtAddEmployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAddEmployee().setVisible(true);
            }
        });
    }
    
    public void resetFields(){
        this.fieldName.setText("");
        this.fieldLastName.setText("");
        this.fieldDocument.setText("");
        this.fieldPost.setText("");
        this.fieldPhone.setText("");
        this.fieldEntryDate.setText("");
        this.fieldSalary.setText("");
        this.boxTermporary.setSelectedItem("Elegir opcion");
    }
    
    public void setEmployees(Employees emp){
        this.employee = emp;
    }
    
    public void showMessage(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTermporary;
    private javax.swing.JPanel btnAddEmployee;
    private javax.swing.JPanel btnBack;
    private javax.swing.JTextField fieldDocument;
    private javax.swing.JTextField fieldEntryDate;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPost;
    private javax.swing.JTextField fieldSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel txtAddEmployee;
    private javax.swing.JLabel txtBack;
    // End of variables declaration//GEN-END:variables
}
