/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employees;

import java.awt.Color;

/**
 *
 * @author Jose Felipe
 */
public class ViewUpdateEmployee extends javax.swing.JFrame {

    private Employees employee;
    
    public ViewUpdateEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        fieldPost = new javax.swing.JTextField();
        fieldName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        fieldSalary = new javax.swing.JTextField();
        fieldDocument = new javax.swing.JTextField();
        fieldEntryDate = new javax.swing.JTextField();
        boxTemporary = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JPanel();
        txtUpdate = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        txtBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 65, 65));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("Actualizar empleado");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 138, 180, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 10));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 10));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 180, -1));

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, 10));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 180, -1));

        fieldPost.setBackground(new java.awt.Color(220, 220, 220));
        fieldPost.setBorder(null);
        jPanel1.add(fieldPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 32));

        fieldName.setBackground(new java.awt.Color(220, 220, 220));
        fieldName.setBorder(null);
        jPanel1.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 32));

        fieldLastName.setBackground(new java.awt.Color(220, 220, 220));
        fieldLastName.setBorder(null);
        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 32));

        fieldPhone.setBackground(new java.awt.Color(220, 220, 220));
        fieldPhone.setBorder(null);
        jPanel1.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 32));

        fieldSalary.setBackground(new java.awt.Color(220, 220, 220));
        fieldSalary.setBorder(null);
        jPanel1.add(fieldSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 180, 32));

        fieldDocument.setBackground(new java.awt.Color(220, 220, 220));
        fieldDocument.setBorder(null);
        jPanel1.add(fieldDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 32));

        fieldEntryDate.setBackground(new java.awt.Color(220, 220, 220));
        fieldEntryDate.setBorder(null);
        jPanel1.add(fieldEntryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 180, 32));

        boxTemporary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir opcion", "Si", "No" }));
        jPanel1.add(boxTemporary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 130, 32));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("¿Es temporal?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Ingresa el nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ingresa el apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Ingresa el numero de documento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Ingresa el cargo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Ingresa el numero de telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Ingresa la fecha de ingreso (DD/MM/AA):");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ingresa el salario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_small.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 260, 170));

        btnUpdate.setBackground(new java.awt.Color(255, 65, 65));

        txtUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUpdate.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUpdate.setText("Actualizar");
        txtUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUpdateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 130, 35));

        btnBack.setBackground(new java.awt.Color(255, 65, 65));

        txtBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBack.setForeground(new java.awt.Color(255, 255, 255));
        txtBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBack.setText("Regresar");
        txtBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void txtBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseEntered
        this.btnBack.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtBackMouseEntered

    private void txtBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseExited
        this.btnBack.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtBackMouseExited

    private void txtUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpdateMouseEntered
        this.btnUpdate.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtUpdateMouseEntered

    private void txtUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpdateMouseExited
         this.btnUpdate.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtUpdateMouseExited

    private void txtBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBackMouseClicked
        this.employee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtBackMouseClicked

    private void txtUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUpdateMouseClicked
        String name = this.fieldName.getText();
        String lastName = this.fieldLastName.getText();
        String document = this.fieldDocument.getText();
        String post = this.fieldPost.getText();
        String phone = this.fieldPhone.getText();
        String date = this.fieldEntryDate.getText();
        String salary = this.fieldSalary.getText();
        String temporary = this.boxTemporary.getSelectedItem().toString();
        
        this.employee.updateEmployee(document, name, lastName, post, phone, date, salary, temporary);
    }//GEN-LAST:event_txtUpdateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUpdateEmployee().setVisible(true);
            }
        });
    }
    public void setName(String name){
        this.txtName.setText("Actualizar empleado "+name);
    }
    
    public void resetFields(){
        this.fieldName.setText("");
        this.fieldLastName.setText("");
        this.fieldDocument.setText("");
        this.fieldPost.setText("");
        this.fieldPhone.setText("");
        this.fieldEntryDate.setText("");
        this.fieldSalary.setText("");
        this.boxTemporary.setSelectedItem("Elegir opcion");
    }
    
    public void setEmployee(Employees emp){
        this.employee = emp;
    }
    
    public void showMessage(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTemporary;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JTextField fieldDocument;
    private javax.swing.JTextField fieldEntryDate;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPost;
    private javax.swing.JTextField fieldSalary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel txtBack;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtUpdate;
    // End of variables declaration//GEN-END:variables
}
