/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manager;
import java.awt.Color;
import sesion.Login;
import employees.Employees;
import performance.ViewPerformance;
/**
 *
 * @author Jose Felipe
 */
public class Manager extends javax.swing.JFrame {

    private Login login;
    private Employees emp;
    private ViewPerformance viPerformance;
    
    public Manager() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.emp = new Employees();
        this.viPerformance = new ViewPerformance();
        this.viPerformance.setEmployees(this.emp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtManager = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCloseSesion = new javax.swing.JPanel();
        txtCloseSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JPanel();
        txtEmployees = new javax.swing.JLabel();
        btnDepartament = new javax.swing.JPanel();
        txtDepartament = new javax.swing.JLabel();
        btnPerformance = new javax.swing.JPanel();
        txtPerformance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 65, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel general");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 590, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 50));

        txtManager.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtManager.setForeground(new java.awt.Color(51, 51, 51));
        txtManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtManager.setText("Bienvenido");
        jPanel1.add(txtManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_small.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 230, 180));

        btnCloseSesion.setBackground(new java.awt.Color(255, 65, 65));

        txtCloseSesion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtCloseSesion.setForeground(new java.awt.Color(255, 255, 255));
        txtCloseSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCloseSesion.setText("Cerrar Sesion");
        txtCloseSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCloseSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCloseSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseSesionLayout = new javax.swing.GroupLayout(btnCloseSesion);
        btnCloseSesion.setLayout(btnCloseSesionLayout);
        btnCloseSesionLayout.setHorizontalGroup(
            btnCloseSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCloseSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        btnCloseSesionLayout.setVerticalGroup(
            btnCloseSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCloseSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(btnCloseSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 125, 34));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("¿Que area desea gestionar?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));

        btnEmployees.setBackground(new java.awt.Color(255, 65, 65));

        txtEmployees.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEmployees.setForeground(new java.awt.Color(255, 255, 255));
        txtEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEmployees.setText("Empleados");
        txtEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmployeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEmployeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEmployeesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEmployeesLayout = new javax.swing.GroupLayout(btnEmployees);
        btnEmployees.setLayout(btnEmployeesLayout);
        btnEmployeesLayout.setHorizontalGroup(
            btnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEmployeesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnEmployeesLayout.setVerticalGroup(
            btnEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEmployeesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 130, 34));

        btnDepartament.setBackground(new java.awt.Color(255, 65, 65));

        txtDepartament.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDepartament.setForeground(new java.awt.Color(255, 255, 255));
        txtDepartament.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDepartament.setText("Departamentos");
        txtDepartament.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDepartament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDepartamentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDepartamentMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDepartamentLayout = new javax.swing.GroupLayout(btnDepartament);
        btnDepartament.setLayout(btnDepartamentLayout);
        btnDepartamentLayout.setHorizontalGroup(
            btnDepartamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDepartamentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDepartamentLayout.setVerticalGroup(
            btnDepartamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDepartamentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnDepartament, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnPerformance.setBackground(new java.awt.Color(255, 65, 65));

        txtPerformance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPerformance.setForeground(new java.awt.Color(255, 255, 255));
        txtPerformance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPerformance.setText("Desempeño");
        txtPerformance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtPerformance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPerformanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPerformanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPerformanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPerformanceLayout = new javax.swing.GroupLayout(btnPerformance);
        btnPerformance.setLayout(btnPerformanceLayout);
        btnPerformanceLayout.setHorizontalGroup(
            btnPerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPerformanceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPerformanceLayout.setVerticalGroup(
            btnPerformanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPerformanceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnPerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCloseSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseClicked
        this.login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtCloseSesionMouseClicked

    private void txtCloseSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseEntered
        this.btnCloseSesion.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtCloseSesionMouseEntered

    private void txtCloseSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCloseSesionMouseExited
        this.btnCloseSesion.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtCloseSesionMouseExited

    private void txtEmployeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmployeesMouseEntered
        this.btnEmployees.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtEmployeesMouseEntered

    private void txtEmployeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmployeesMouseExited
        this.btnEmployees.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtEmployeesMouseExited

    private void txtDepartamentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDepartamentMouseEntered
        this.btnDepartament.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtDepartamentMouseEntered

    private void txtDepartamentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDepartamentMouseExited
        this.btnDepartament.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtDepartamentMouseExited

    private void txtPerformanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPerformanceMouseEntered
        this.btnPerformance.setBackground(new Color(200,50,50));
    }//GEN-LAST:event_txtPerformanceMouseEntered

    private void txtPerformanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPerformanceMouseExited
        this.btnPerformance.setBackground(new Color(255,65,65));
    }//GEN-LAST:event_txtPerformanceMouseExited

    private void txtEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmployeesMouseClicked
       this.emp.setManager(this);
       this.emp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_txtEmployeesMouseClicked

    private void txtPerformanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPerformanceMouseClicked
        this.viPerformance.setManager(this);
        this.viPerformance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtPerformanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }
    
    public void setManager(String name){
        this.txtManager.setText("Bienvenid@ "+name);
    }
    
    public void setLogin(Login login){
        this.login = login;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseSesion;
    private javax.swing.JPanel btnDepartament;
    private javax.swing.JPanel btnEmployees;
    private javax.swing.JPanel btnPerformance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCloseSesion;
    private javax.swing.JLabel txtDepartament;
    private javax.swing.JLabel txtEmployees;
    private javax.swing.JLabel txtManager;
    private javax.swing.JLabel txtPerformance;
    // End of variables declaration//GEN-END:variables
}
